# -*- coding: utf-8 -*-
"""Python Basics - Module 03.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Tzex9dzC7lcrBNTXVwy9qo8zR_QS0VNd

Abrindo e fechando arquivos

Podemos criar arquivos novos ou abrir arquivos já existentes utilizando a função open. Ela possui 2 argumentos: o caminho do arquivo e o modo de operação.

Modo	Símbolo	Descrição

read	r	lê um arquivo existente

write	w	cria um novo arquivo

append	a	abre um arquivo existente para adicionar informações ao seu final

update	+	ao ser combinado com outros modos, permite alteração de arquivo já existente (ex: r+ abre um arquivo existente e permite modificá-lo
"""

from google.colab import drive
drive.mount('/content/drive')

"""#Manipulação de Arquivos"""

arquivo = open("/content/drive/My Drive/Colab Notebooks/Santander Coders - Data Science/dom_casmurro_cap_1.txt","r")

dados = arquivo.read()
print(dados)

#OU

with open('/content/drive/My Drive/Colab Notebooks/Santander Coders - Data Science/dom_casmurro_cap_1.txt', 'r') as arquivo2:
   dados2 = arquivo2.read()
   print(dados2)

#LENDO LINHA A LINHA - EX

with open('teste.txt', 'r') as arquivolido:
   linha = arquivolido.readline()
   while linha != '':
       print(linha, end='')
       linha = arquivolido.readline()


# OU

with open('teste.txt', 'r') as arquivolido:
    for linha in arquivolido:
        print(linha, end='')

#O mesmo pode ser feito para escrever linha a linha no arquivo:

with open('teste.txt', 'r') as arquivolido:
    with open('copiateste.txt', 'w') as arquivocriado:
        for linha in arquivolido:
            arquivocriado.write(linha)

#fechando o arquivo

arquivo.close()

"""#Arquivos CSV"""

import csv

with open('/content/drive/My Drive/Colab Notebooks/Santander Coders - Data Science/brasilcovid.csv', 'r', encoding='utf-8') as file:
   covid_data = csv.reader(file)
   next(covid_data) #pula o header
   for linha in covid_data:
      if float(linha[2]) > 1: #novos casos>1
        print(linha)

#escrevendo novo csv

with open('/content/drive/My Drive/Colab Notebooks/Santander Coders - Data Science/novo_users.csv','w',encoding='utf-8', newline='') as file2:
  datawriter = csv.writer(file2)
  datawriter.writerow(['nome','sobrenome','idade','sexo'])
  datawriter.writerow(['welliton','leal','27','masculino'])

#exemplo de cadastro

header = ['nome','sobrenome']
dados3 = []
opt = input('O que deseja fazer? \n1 - Cadastro \n 0 - Sair\n')
while opt!= '0':
  nome = input("Qual seu nome?")
  sobrenome = input("Qual seu sobrenome?")
  dados3.append([nome,sobrenome])
  opt = input('O que deseja fazer? \n1 - Cadastro \n 0 - Sair\n')

print(dados3)

with open('/content/drive/My Drive/Colab Notebooks/Santander Coders - Data Science/cadastro.csv','w',encoding='utf-8', newline='') as file3:
  writer = csv.writer(file3)
  writer.writerow(header)
  writer.writerow(dados3)

with open('/content/drive/My Drive/Colab Notebooks/Santander Coders - Data Science/cadastro.csv', 'r') as file:
  csv_reader = csv.reader(file, delimiter=',')
  for row in csv_reader:
      print(row)

"""#API's"""

!pip install requests

import requests

url = 'https://api.exchangerate-api.com/v6/latest'

req = requests.get(url)

print(req.status_code)

data = req.json()
print(data)

valor_reais = float(input('Informe o valor em R$ a ser convertido\n'))
cotacao = data['rates']['BRL']
print(f'R$ {valor_reais} em dólar valem US$ {(valor_reais / cotacao):.2f}')